### PR TITLE
Added function for deleting a file from the remote server given a pat…

### PR DESCRIPTION
**Pull request by branallen**
…h to the remote file.

### CODE REVIEW

**Comment by branallen** [comment]
@agnash hey I followed the workflow and didn't see any conflicts locally but its saying there are conflicts on the branch I created. The project still built successfully though.

**Comment by agnash** [comment]
I'll take a look and make any necessary commits to your branch.

**Comment by agnash** [comment]
@branallen fixed. Go ahead and complete the merge.

**Comment by agnash** [comment]
@branallen I'll go ahead and completed the merge on this, thx.

**Comment by branallen** [comment]
Thanks for doing that. Was it a windows issue? Sorry I stepped away fromy
computer.

**Comment by agnash** [comment]
Doubt it. I think maybe Sergio squeezed in another merge sometime between you doing steps 2 and 3 in the git workflow therefore making your branch out of date with develop again. Conflicts are inevitable so it's all good!

**Pull request merged**
